version: "2"
services:
  radarr4k:
    image: linuxserver/radarr:latest
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/radarr4k:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr4k.rule=Host(`${HOST}`)
      - traefik.http.services.radarr4k.loadbalancer.server.port=7878
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
