version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    volumes:
      - /config/sonarr:/config
      - /mnt/downloads:/downloads
      - /mnt/tv:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:sonarr.home.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
