version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/data
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${HOST}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
