version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${HOST}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.tls.certresolver=le
      - traefik.http.routers.sonarr.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
