version: "2"
services:
  tautulli:
    image: linuxserver/tautulli:develop
    container_name: tautulli
    volumes:
      - /Pool/Docker/tautulli:/config
      - /Pool/Downloads:/downloads
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.port=8181"
      - "traefik.frontend.rule=Host:tautulli.home.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
