version: "2"
services:
  tautulli:
    image: linuxserver/tautulli:develop
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`${HOST}`)
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
      - traefik.http.routers.tautulli.tls.certresolver=le
      - traefik.http.routers.tautulli.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
