version: "2"
services:
  tautulli:
    image: linuxserver/tautulli:develop
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`${HOST}`)
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
    external: true
