version: "2"
services:
  sonarr4k:
    image: linuxserver/sonarr:develop
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/sonarr4k:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr4k.rule=Host(`${HOST}`)
      - traefik.http.services.sonarr4k.loadbalancer.server.port=8989
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
