version: "2"
services:
  sonarr4k:
    image: linuxserver/sonarr:develop
    volumes:
      - ${CONFIG_DIR}/sonarr4k:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr4k.rule=Host(`${HOST}`)
      - traefik.http.services.sonarr4k.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr4k.tls.certresolver=le
      - traefik.http.routers.sonarr4k.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
