version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: unless-stopped
    links:
      - database
    volumes:
      - ${CONFIG_DIR}/mediawiki/images:/var/www/html/images
      - ${CONFIG_DIR}/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`${HOST}`)
      - traefik.http.services.wiki.loadbalancer.server.port=80
      - traefik.http.routers.wiki.tls.certresolver=le
      - traefik.http.routers.wiki.entrypoints=websecure
    networks:
      default:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
      