version: "2"
services:
  ombi:
    image: linuxserver/ombi:development
    container_name: ombi
    volumes:
      - /Pool/Docker/ombi:/config
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.port=3579"
      - "traefik.frontend.rule=Host:requests.plex.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
