version: "2"
services:
  ombi:
    image: linuxserver/ombi:development
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/ombi:/config
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`${HOST}`)
      - traefik.http.services.ombi.loadbalancer.server.port=3579
      - traefik.http.routers.ombi.tls.certresolver=le
      - traefik.http.routers.ombi.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
