version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`${HOST}`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
