version: "2.1"
services:
  tdarr:
    image: haveagitgat/tdarr:latest
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/tdarr/server:/app/server
      - ${CONFIG_DIR}/tdarr/configs:/app/configs
      - ${CONFIG_DIR}/tdarr/logs:/app/logs
      - ${CONFIG_DIR}/tdarr/transcode_cache:/temp
      - ${MOVIES_DIR}:/media/movies
      - ${TV_DIR}:/media/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      - ROOT_URL=https://${HOST}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    ports:
      - 8266:8266
      - 8267:8267
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`${HOST}`)
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    networks:
      default:
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      - nodeID=MainNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - serverIP=0.0.0.0
      - serverPort=8266
    volumes:
      - ${CONFIG_DIR}/tdarr/server:/app/server
      - ${CONFIG_DIR}/tdarr/configs:/app/configs
      - ${CONFIG_DIR}/tdarr/logs:/app/logs
      - ${CONFIG_DIR}/tdarr/transcode_cache:/temp
      - ${MOVIES_DIR}:/media/movies
      - ${TV_DIR}:/media/tv
networks:
  default:
    name: ${TRAEFIK_NETWORK}
