version: "2"
services:
  roon:
    image: steefdebruijn/docker-roonserver:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/roon/app:/app
      - ${CONFIG_DIR}/roon/data:/data
      - ${CONFIG_DIR}/roon/backup:/backup
      - ${MUSIC_DIR}:/music
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=false
