version: "2"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    hostname: ${HOST}
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/plex/config:/config
      - ${CONFIG_DIR}/plex/tmp:/tmp
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
      - ${MUSIC_DIR}:/music
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      - VERSION=latest
