version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=1020
      - PGID=1020
      - VERSION=latest
      - TZ=America/New_York
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${CONFIG_DIR}/plex/config:/config
      - ${POOL_DIR}/Movies:/movies
      - ${POOL_DIR}/TVShows:/tv
      - ${POOL_DIR}/Music:/music
