version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${CONFIG_DIR}/plex/transcode:/transcode
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
      - ${MUSIC_DIR}:/music
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      - VERSION=latest
