version: "2"
services:
  komga:
    image: gotson/komga:latest-legacy
    restart: unless-stopped
    hostname: ${HOST}
    user: 1020:1020
    volumes:
      - ${CONFIG_DIR}/komga:/config
      - ${COMICS_DIR}:/data
      - /etc/timezone:/etc/timezone
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.books.rule=Host(`${HOST}`)
      - traefik.http.services.books.loadbalancer.server.port=8080
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
