version: "2"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${MEDIA_DIR}/downloads/sabnzbd/complete:/data/downloads/
      - ${MEDIA_DIR}/downloads/sabnzbd/incomplete:/data/incomplete-downloads/
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`${HOST}`)
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
    external: true
