version: "2"
services:
  musicbot-primary:
    image: ghcr.io/akpwebdesign/octave/music-bot:latest
    hostname: musicbot-primary
    environment:
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/musicbot/primary/config:/app/config
    restart: unless-stopped
    depends_on:
      - redis-primary
      - rethink-primary

  redis-primary:
    image: redis
    restart: unless-stopped
    hostname: musicbot-redis-primary

  rethink-primary:
    image: rethinkdb
    restart: unless-stopped
    hostname: musicbot-rethink-primary
    ports:
      - 4735:8080
    volumes:
      - ${CONFIG_DIR}/musicbot/primary/rethink:/data

  musicbot-secondary:
    image: ghcr.io/akpwebdesign/octave/music-bot:latest
    hostname: musicbot-secondary
    environment:
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/musicbot/secondary/config:/app/config
    restart: unless-stopped
    depends_on:
      - redis-secondary
      - rethink-secondary

  redis-secondary:
    image: redis
    restart: unless-stopped
    hostname: musicbot-redis-secondary

  rethink-secondary:
    image: rethinkdb
    restart: unless-stopped
    hostname: musicbot-rethink-secondary
    ports:
      - 5783:8080
    volumes:
      - ${CONFIG_DIR}/musicbot/secondary/rethink:/data
