version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz
    container_name: netbootxyz
    hostname: ${HOST}
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/netbootxyz/config:/config
      - ${CONFIG_DIR}/netbootxyz/assets:/assets
    ports:
      - 69:69/udp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbootconf.rule=Host(`${HOST}`)
      - traefik.http.services.netbootconf.loadbalancer.server.port=3000
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
