version: "3.7"
services:
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${MEDIA_DIR}/downloads:/data/downloads
    restart: always
    user: 1020:1020
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      # General config
      - UN_DEBUG=false
      - UN_INTERVAL=1m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Sonarr 4K Config
      - UN_SONARR_1_URL=http://sonarr4k:8989
      - UN_SONARR_1_API_KEY=${SONARR_API_KEY}
      - UN_SONARR_1_PATHS_0=/downloads
      - UN_SONARR_1_PROTOCOLS=torrent
      - UN_SONARR_1_TIMEOUT=10s
      - UN_SONARR_1_DELETE_ORIG=false
      - UN_SONARR_1_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Radarr 4K Config
      - UN_RADARR_1_URL=http://radarr4k:7878
      - UN_RADARR_1_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_1_PATHS_0=/downloads
      - UN_RADARR_1_PROTOCOLS=torrent
      - UN_RADARR_1_TIMEOUT=10s
      - UN_RADARR_1_DELETE_ORIG=false
      - UN_RADARR_1_DELETE_DELAY=5m
      # Lidarr Config
      - UN_LIDARR_0_URL=http://lidarr:8686
      - UN_LIDARR_0_API_KEY=${LIDARR_API_KEY}
      - UN_LIDARR_0_PATHS_0=/downloads
      - UN_LIDARR_0_PROTOCOLS=torrent
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=false
      - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://readarr:8787
      - UN_READARR_0_API_KEY=${READARR_API_KEY}
      - UN_READARR_0_PATHS_0=/downloads
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m
      # Webhook Config
      - UN_WEBHOOK_0_URL=${DISCORD_WEBHOOK_URL}
      - UN_WEBHOOK_0_NAME=Discord
      - UN_WEBHOOK_0_NICKNAME=Unpackerr
      - UN_WEBHOOK_0_SILENT=true
      - UN_WEBHOOK_0_IGNORE_SSL=false
      - UN_WEBHOOK_0_EXCLUDE_0=
      - UN_WEBHOOK_0_EVENTS_0=0
      - UN_WEBHOOK_0_TEMPLATE=discord
      - UN_WEBHOOK_0_CONTENT_TYPE=application/json
    security_opt:
      - no-new-privileges:true
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
