version: "2"
services:
  send:
    image: mozilla/send:latest
    restart: unless-stopped
    links:
      - redis
    volumes:
      - ${STORAGE_DIR}:/send
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - FXA_REQUIRED=false
      - ANON_MAX_DOWNLOADS=500000
      - ANON_MAX_FILE_SIZE=2147483648
      - ANON_MAX_EXPIRE_SECONDS=31556952
      - DOWNLOAD_COUNTS=1, 5, 20, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 500000
      - EXPIRE_TIMES_SECONDS=300, 3600, 86400, 604800, 2592000, 7776000, 31556952
      - BASE_URL=https://${HOST}
      - FILE_DIR=/send
    labels:
      - traefik.enable=true
      - traefik.http.routers.send.rule=Host(`${HOST}`)
      - traefik.http.services.send.loadbalancer.server.port=1443
      - traefik.http.routers.send.tls.certresolver=le
      - traefik.http.routers.send.entrypoints=websecure
    networks:
      default:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
