version: "2"
services:
  traefik:
    image: traefik:v2.7
    restart: unless-stopped
    hostname: ${HOST}
    command:
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/rules/
      - --api
      - --metrics
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      - --metrics.prometheus.addRoutersLabels=true
      - --pilot.token=${TRAEFIK_PILOT_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR}/traefik/acme.json:/acme.json
      - ${CONFIG_DIR}/traefik/rules/:/rules/
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`${HOST}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web
    networks:
      default:

networks:
  default:
    name: ${TRAEFIK_NETWORK}
