version: "2"
services:
  transmission:
    image: traefik:maroilles
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/config/traefik/traefik.toml:/traefik.toml
      - /mnt/config/traefik/acme.json:/acme.json
      - /mnt/config/traefik/rules/:/rules/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.home.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
