version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_DIR}/data:/data
      - ${NEXTCLOUD_DIR}/config:/config
    links:
      - postgres
      - redis
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${HOST}`)
      - traefik.http.routers.nextcloud.tls.certresolver=le
      - traefik.http.routers.nextcloud.entrypoints=websecure
    networks:
      default:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      default:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${NEXTCLOUD_DIR}/database:/var/lib/postgresql/data
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
