rancher:
  services:
    configcopier:
      image: akpwd/rsync
      command: sh -c "rsync -r /config/ /mnt/config && chown -R 1020:1020 /mnt/config/ && sleep 1h"
      restart: always
      container_name: config-copier
      labels:
        io.rancher.os.after: console, preload-user-images
      volumes:
        - /mnt/config:/mnt/config
        - /config:/config
