version: "2"
services:
  jackett:
    image: linuxserver/jackett:development
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`${HOST}`)
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.http.routers.jackett.tls.certresolver=le
      - traefik.http.routers.jackett.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
