version: "2"
services:
  jackett:
    image: linuxserver/jackett:development
    container_name: jackett
    volumes:
      - /Pool/Docker/jackett:/config
      - /Pool/Downloads:/downloads
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.port=9117"
      - "traefik.frontend.rule=Host:jackett.home.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
