version: "2.4"
services:
  influxdb:
    image: influxdb:2.2
    hostname: scrutiny-influx
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - "${CONFIG_DIR}/scrutiny/influxdb:/var/lib/influxdb2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      default:

  web:
    image: ghcr.io/analogj/scrutiny:master-web
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/scrutiny:/opt/scrutiny/config
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=influxdb
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrutiny.rule=Host(`${HOST}`)
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      default:

  collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    restart: unless-stopped
    hostname: scrutiny-collector
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - COLLECTOR_API_ENDPOINT=http://web:8080
    volumes:
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
      - /dev/sdk:/dev/sdk
      - /dev/sdl:/dev/sdl
    networks:
      default:
    depends_on:
      web:
        condition: service_healthy
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
