version: "2"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    hostname: cloudflared
    restart: unless-stopped
    container_name: cloudflared
    command: "tunnel run --token ${CF_TOKEN}"
    user: root
    volumes:
      - ${CONFIG_DIR}:/etc/cloudflared/
    networks:
      default:

networks:
  default:
    name: ${TRAEFIK_NETWORK}
