FROM gcr.io/datadoghq/agent:latest
RUN agent integration install -r -t datadog-traefik==1.1.0
RUN agent integration install -r -t datadog-sonarr==1.0.0
RUN agent integration install -r -t datadog-radarr==1.0.0
