version: "2"
services:
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DOWNLOADS_DIR}/nzbget/:/downloads/
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget.rule=Host(`${HOST}`)
      - traefik.http.services.nzbget.loadbalancer.server.port=6789
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
