version: "2"
services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
    labels:
      traefik.enable: "true"
      traefik.backend: nzbget
      traefik.port: "6789"
      traefik.frontend.rule: "Host:nzbget.home.akp.tools"
    volumes:
      - /Pool/Docker/nzbget:/config
      - /Pool/Downloads/nzbget/:/downloads/
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
