version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin:nightly
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MOVIES_DIR}:/data/movies
      - ${TV_DIR}:/data/tv
      - ${MUSIC_DIR}:/data/music
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
      - VERSION=latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${HOST}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.tls.certresolver=le
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
