version: "2"
services:
  spotify:
    image: docker.pkg.github.com/akpwebdesign/spotify-widget/spotify-widget:latest
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.spotify.rule=Host(`${HOST}`)
      - traefik.http.routers.spotify.tls.certresolver=le
      - traefik.http.routers.spotify.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
