version: "2"
services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/portainer:/data
    environment:
      PGID: '1020'
      PUID: '1020'
      TZ: America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${HOST}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.tls.certresolver=le
      - traefik.http.routers.portainer.entrypoints=websecure
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
