version: "2"
services:
  mylar3:
    image: linuxserver/mylar3:nightly
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/mylar3:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${COMICS_DIR}:/comics
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.mylar3.rule=Host(`${HOST}`)
      - traefik.http.services.mylar3.loadbalancer.server.port=8090
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
