version: "2"
services:
  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`${HOST}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
