version: "2"
services:
  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/tv:/tv
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`${HOST}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    networks:
      default:
networks:
  default:
    name: ${TRAEFIK_NETWORK}
