version: "2.1"
services:
  homebridge:
    image: oznu/homebridge:latest
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/homebridge:/homebridge
    network_mode: host
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    restart: unless-stopped
