version: "2"
services:
  lidarr:
    image: linuxserver/lidarr:nightly
    hostname: ${HOST}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MUSIC_DIR}:/music
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`${HOST}`)
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
