version: '3'
services:
  perforce:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/p4/data:/perforce-data
      - ${CONFIG_DIR}/p4/dbs:/dbs
      - ./p4dctl.conf.d:/etc/perforce/p4dctl.conf.d
    environment:
      - P4PORT=1666
      - P4ROOT=/perforce-data
    ports:
      - 1666:1666
# TODO: make traefik work
#     labels:
#       - traefik.enable=true
#       - traefik.http.routers.p4.rule=Host(`${HOST}`)
#       - traefik.http.routers.p4.entrypoints=p4
#       - traefik.http.routers.p4.service=perforce
#       - traefik.http.services.p4.loadbalancer.server.port=1666
#       - traefik.http.routers.p4.tls.certresolver=le
#     networks:
#       default:
# networks:
#   default:
#     external:
#       name: ${TRAEFIK_NETWORK}
