version: "2"
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    hostname: ${HOST}
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.rule=Host(`${HOST}`)
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
