version: "2"
services:
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    environment:
      - PUID=1020
      - PGID=1020
      - TZ=America/Los_Angeles
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - /Pool/Docker/transmission:/config
      - /Pool/Downloads/transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.home.akp.tools`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.tls.certresolver=le
      - traefik.http.routers.transmission.entrypoints=websecure
    networks:
      default:

networks:
  default:
    external:
      name: traefik_net
