version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    volumes:
      - /mnt/config/transmission:/config
      - /mnt/downloads/transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.port=9091"
      - "traefik.frontend.rule=Host:transmission.home.akp.tools"
    networks:
      default:
networks:
  default:
    external:
      name: traefik_net
