version: "2"
services:
  logspout:
    image: gliderlabs/logspout:latest
    hostname: logspout
    command: "${SYSLOG_DEST}"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/New_York
