version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    labels:
      - traefik.enable=false
    networks:
      default:
networks:
  default:
    external:
      name: ${TRAEFIK_NETWORK}
