version: "2"
services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 1935:1935

# TODO: consider adding a tcp traefik config for this
