version: "2"
services:
  gulagbot:
    image: docker.pkg.github.com/akpwebdesign/gulag-bot/gulag-bot:latest
    environment:
      - TOKEN=${DISCORD_TOKEN}
      - TZ=America/New_York
    restart: unless-stopped
